/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codedoc;

import static codedoc.LoginWindow.soc;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;


import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintStream;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;


import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Caret;
import javax.swing.text.Document;

import static java.util.stream.DoubleStream.builder;
import static java.util.stream.IntStream.builder;

import javax.swing.Box;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Asmita Yadav
 */
public class CodeDoc extends javax.swing.JFrame {
    public String ClientIDToShare;
    PrintWriter out;
    BufferedReader in;
    int k = 0;
    int l= 1;
    private Document model;
    private transient Caret caret;
    boolean sender= false;
    boolean codeArea= false;
    boolean chatArea= false;
    /**
     * Creates new form CodeDoc
     */


    int exit=0;
    int sec=0;
    public static String path=null;
    private static final String FILE_LOCATION1 ="Desktop\\winners\\codeDOC\\codeDOC\\arya.c";    
     private static final String FILE_LOCATION2 ="Desktop\\winners\\codeDOC\\codeDOC\\arya.py";
     private static final String FILE_LOCATION3 ="Desktop\\winners\\codeDOC\\codeDOC\\arya.cpp";
     
     private static final String FILE_LOCATION4 ="Desktop\\winners\\codeDOC\\codeDOC\\arya.java";
     
   
    
   
    public CodeDoc() {
        try
        { out=new PrintWriter(soc.getOutputStream(),true);
          in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
        }
         catch (Exception ex)
        {System.out.println("Exception : " + ex);}

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        newDoc = new javax.swing.JButton();
        editDoc = new javax.swing.JButton();
        saveDoc = new javax.swing.JButton();
        shareButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Open = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        chatSection = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        typeMessg = new javax.swing.JTextArea();
        sendMessage = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        compiletextbox = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        languageSelector = new javax.swing.JComboBox<>();
        autoComplete = new javax.swing.JCheckBox();
        reset = new javax.swing.JButton();
        fontSetting = new javax.swing.JButton();
        press = new javax.swing.JButton();
        release = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        customInput = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        getinput = new javax.swing.JTextArea();
        compileAndRun = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        getoutput = new javax.swing.JTextArea();

        timer = new javax.swing.JTextField();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextField1.setText("CodeDOC");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        newDoc.setText("New");
        newDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDocActionPerformed(evt);
            }
        });

        editDoc.setText("Edit");
        editDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDocActionPerformed(evt);
            }
        });

        saveDoc.setText("Save");
        saveDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDocActionPerformed(evt);
            }
        });

        shareButton.setText("Share");

        shareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareButtonActionPerformed(evt);
            }
        });


        jButton2.setText("Chat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Audio Call");

        jButton5.setText("Video Call");

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newDoc)
                .addGap(18, 18, 18)
                .addComponent(editDoc)
                .addGap(18, 18, 18)
                .addComponent(saveDoc)
                .addGap(18, 18, 18)
                .addComponent(Open)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shareButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDoc)
                    .addComponent(editDoc)
                    .addComponent(saveDoc)
                    .addComponent(shareButton)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(Open))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        chatSection.setColumns(20);
        chatSection.setRows(5);
        jScrollPane4.setViewportView(chatSection);

        typeMessg.setColumns(20);
        typeMessg.setRows(5);
        jScrollPane5.setViewportView(typeMessg);

        sendMessage.setText("Send");
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });

        compiletextbox.setColumns(20);
        compiletextbox.setRows(5);
        compiletextbox.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                compiletextboxCaretUpdate(evt);
            }
        });
        compiletextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                compiletextboxKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(compiletextbox);

        compiletextbox.setColumns(20);
        compiletextbox.setRows(5);
        jScrollPane6.setViewportView(compiletextbox);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()

                .addContainerGap()

                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(sendMessage)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))

                .addComponent(sendMessage))
        );

        jPanel3.setBackground(new java.awt.Color(212, 239, 242));

        languageSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C++", "Java", "Python" }));

        autoComplete.setText("Autocomplete");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        fontSetting.setText("Font Setting");
        fontSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontSettingActionPerformed(evt);
            }
        });

        press.setText("Press");
        press.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressActionPerformed(evt);
            }
        });

        release.setText("Release");
        release.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(languageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autoComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(reset)
                .addGap(18, 18, 18)
                .addComponent(fontSetting)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                .addComponent(press)
                .addGap(70, 70, 70)
                .addComponent(release)
                .addGap(153, 153, 153))

        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoComplete)
                    .addComponent(reset)
                    .addComponent(fontSetting)
                    .addComponent(press)
                    .addComponent(release))
                .addContainerGap())
        );

        customInput.setText("Custom Input");
        customInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customInputActionPerformed(evt);
            }
        });

        getinput.setColumns(20);
        getinput.setRows(5);
        jScrollPane1.setViewportView(getinput);

        compileAndRun.setText("Compile & Run");
        compileAndRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileAndRunActionPerformed(evt);
            }
        });

        getoutput.setColumns(20);
        getoutput.setRows(5);
        jScrollPane3.setViewportView(getoutput);


        timer.setText("Seconds");


        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(compileAndRun))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(compileAndRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customInput))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 279, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    /*//
     !!!!!!!!!!!!!!!!!text area shi krna hai
     public Color textColor;
     public void setTextFont(Font font) {
        textArea.setFont(font);  
        textArea.setForeground(textColor);
    }    
     
   //*/
    public Document getDocument() {
        return model;
    }
    

//Get files from open dialog box 
    String data1;
    static String data="";
   
    public void showContent(String path)
    {   
        data="";
        try
        {
            File myObj=new File(path);
            Scanner myReader = new Scanner(myObj);
            
            while(myReader.hasNextLine())
            {
                data+=myReader.nextLine()+"\n";
            }
            
            compiletextbox.setText(data);
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }
 

    public void setCaretPosition(int position) {
        Document doc = getDocument();
        if (doc != null) {
            if (position > doc.getLength() || position < 0) {
                throw new IllegalArgumentException("bad position: " + position);
            }
            caret.setDot(position);
        }
    }
    public void moveCaretPosition(int pos) {
        Document doc = getDocument();
        if (doc != null) {
            if (pos > doc.getLength() || pos < 0) {
                throw new IllegalArgumentException("bad position: " + pos);
            }
            caret.moveDot(pos);
        }
    }

    
// CUSTOM INPUT
    
    private void customInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customInputActionPerformed

    }//GEN-LAST:event_customInputActionPerformed

// COMPILE AND RUN    
    private void compileAndRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileAndRunActionPerformed


                                      
        
        exit=0;
            String a = languageSelector.getSelectedItem().toString();
            //get the preffered language from user
            int gotsec=Integer.valueOf(timer.getText());
            
            Thread th7=new Thread(new Runnable() {
               @Override
               public void run() {
                  
                  sec=0;
                   while(sec<gotsec && exit==0)
        {
            try {
                Thread.sleep(1000);
                sec++;
                timer.setText(Integer.toString(sec));
            } catch (InterruptedException ex) {
                Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                   if(gotsec<=sec)
                   {
                       getoutput.setText("TLE");
                       return;
                   }
                          
               }
       });
             th7.start();
            if(a.equalsIgnoreCase("C")){
            try {
            String filename = "arya.c";
            FileWriter fileWriter=new FileWriter(filename);
            fileWriter.write(compiletextbox.getText());
            setTitle(filename);
            fileWriter.close();
            } catch (IOException e) {
                exit=1;
            System.out.println("file not found");
            }
            //created a file successfully in the folder where project is cloned
            boolean isWindows = System.getProperty("os.name")
  .toLowerCase().startsWith("windows");
            
             ProcessBuilder processBuilder = new ProcessBuilder();
             Process process=null;
           if (isWindows) {
                   processBuilder.command("cmd.exe", "/c", "gcc",FILE_LOCATION1);
               } else {
                   processBuilder.command("sh", "-c", "ls");
               }
               processBuilder.directory(new File(System.getProperty("user.home")));


                try {
                    process = processBuilder.start();
                    BufferedReader br=new BufferedReader(new InputStreamReader(process.getInputStream()));//getting the output
                    String coutput;
                    while((coutput=br.readLine())!=null)
                    {
                        System.out.println(coutput);
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    if( process.getErrorStream().read() != -1 )
                    {
                        exit=1;
                        getoutput.setText("file cant be compiled " +process.getErrorStream());
  
                        return;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                 
            if (isWindows) {
                   processBuilder.command("cmd.exe", "/c", "a");
               } else {
                   processBuilder.command("sh", "-c", "ls");
               }
                try {
                    process = processBuilder.start();
                    OutputStream os=process.getOutputStream();
                    PrintStream ps = new PrintStream(os);//if we want to send some input
                    ps.println(getinput.getText());
                    ps.flush();
                    BufferedReader br=new BufferedReader(new InputStreamReader(process.getInputStream()));//getting the output
                    String coutput;
                    while((coutput=br.readLine())!=null)
                    {
                        if(sec>=gotsec)
                        {
                            getoutput.setText("TLE");
                            return;
                        }
                        getoutput.setText(coutput);
                        System.out.println(coutput);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 exit=1;
            
        }
            if(a.equalsIgnoreCase("C++")){
            try {
            String filename = "arya.cpp";
            FileWriter fileWriter=new FileWriter(filename);
            fileWriter.write(compiletextbox.getText());
            setTitle(filename);
            fileWriter.close();
            } catch (IOException e) {
            System.out.println("file not found");
            }
            //created a file successfully in the folder where project is cloned
            boolean isWindows = System.getProperty("os.name")
  .toLowerCase().startsWith("windows");
            
             ProcessBuilder processBuilder = new ProcessBuilder();
             Process process=null;
           if (isWindows) {
                   processBuilder.command("cmd.exe", "/c", "g++",FILE_LOCATION3);
               } else {
                   processBuilder.command("sh", "-c", "ls");
               }
               processBuilder.directory(new File(System.getProperty("user.home")));


                try {
                    process = processBuilder.start();
                    BufferedReader br=new BufferedReader(new InputStreamReader(process.getInputStream()));//getting the output
                    String coutput;
                    while((coutput=br.readLine())!=null)
                    {
                        System.out.println(coutput);
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    if( process.getErrorStream().read() != -1 )
                    {
                        exit=1;
                        getoutput.setText("file cant be compiled " +process.getErrorStream());
                        return;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                 
            if (isWindows) {
                   processBuilder.command("cmd.exe", "/c", "a");
               } else {
                   processBuilder.command("sh", "-c", "ls");
               }
                try {
                    process = processBuilder.start();
                    OutputStream os=process.getOutputStream();
                    PrintStream ps = new PrintStream(os);//if we want to send some input
                    BufferedReader br=new BufferedReader(new InputStreamReader(process.getInputStream()));//getting the output
                    String coutput;
                    while((coutput=br.readLine())!=null)
                    {
                        getoutput.setText(coutput);
                        System.out.println(coutput);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
            exit=1;
        }
            if(a.equalsIgnoreCase("java")){
            try {
            String filename = "arya.java";
            FileWriter fileWriter=new FileWriter(filename);
            fileWriter.write(compiletextbox.getText());
            setTitle(filename);
            fileWriter.close();
            } catch (IOException e) {
                exit=1;
                
            getoutput.setText("file not found");
            return;
            }
            //created a file successfully in the folder where project is cloned
            boolean isWindows = System.getProperty("os.name")
  .toLowerCase().startsWith("windows");
            
             ProcessBuilder processBuilder = new ProcessBuilder();
             Process process=null;
           if (isWindows) {
                   processBuilder.command("cmd.exe", "/c", "javac",FILE_LOCATION4);
               } else {
                   processBuilder.command("sh", "-c", "ls");
               }
               processBuilder.directory(new File(System.getProperty("user.home")));


                try {
                    process = processBuilder.start();
                    BufferedReader br=new BufferedReader(new InputStreamReader(process.getInputStream()));//getting the output
                    String coutput;
                    while((coutput=br.readLine())!=null)
                    {
                        
                        System.out.println(coutput);
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    if( process.getErrorStream().read() != -1 )
                    {
                        exit=1;
                        getoutput.setText("file cant be compiled " +process.getErrorStream());
                        return;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                 
            if (isWindows) {
                   processBuilder.command("cmd.exe", "/c", "java","-cp",FILE_LOCATION4);
               } else {
                   processBuilder.command("sh", "-c", "ls");
               }
                try {
                    process = processBuilder.start();
                    OutputStream os=process.getOutputStream();
                    PrintStream ps = new PrintStream(os);//if we want to send some input
                    ps.println(getinput.getText());
                    ps.flush();
                    System.out.println("here");
                    
                    BufferedReader br=new BufferedReader(new InputStreamReader(process.getInputStream()));//getting the output
                    String coutput;
                    while((coutput=br.readLine())!=null)
                    {
                        if(sec>=gotsec)
                        {
                            getoutput.setText("TLE");
                         
                            return;
                        }
                        getoutput.setText(coutput);
                        System.out.println(coutput);
                        
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
            exit=1;
        } 
    if(a.equalsIgnoreCase("python")){
            try {
            String filename = "arya.py";
            FileWriter fileWriter=new FileWriter(filename);
            fileWriter.write(compiletextbox.getText());
            setTitle(filename);
            fileWriter.close();
            } catch (IOException e) {
                exit=1;
            System.out.println("file not found");
            }
            //created a file successfully in the folder where project is cloned
            boolean isWindows = System.getProperty("os.name")
  .toLowerCase().startsWith("windows");
            
             ProcessBuilder processBuilder = new ProcessBuilder();
             Process process=null;
           if (isWindows) {
                   processBuilder.command("cmd.exe", "/c", "py",FILE_LOCATION2);
               } else {
                   processBuilder.command("sh", "-c", "ls");
               }
               processBuilder.directory(new File(System.getProperty("user.home")));


                try {
                    process = processBuilder.start();
                    OutputStream os=process.getOutputStream();
                     PrintStream ps = new PrintStream(os);//if we want to send some input
        
                    ps.println(getinput.getText());
                    ps.flush();
                    
                    System.out.println("here");
                    
                    BufferedReader br=new BufferedReader(new InputStreamReader(process.getInputStream()));//getting the output
                    String coutput;
                    if(sec>=gotsec)
                        {
                            getoutput.setText("TLE");
                         
                            return;
                        }
                    while((coutput=br.readLine())!=null)
                    {
                        if(sec>=gotsec)
                        {
                            getoutput.setText("TLE");
                         
                            return;
                        }
                        getoutput.setText(coutput);
                        System.out.println(coutput);
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    if( process.getErrorStream().read() != -1 )
                    {
                        exit=1;
                        getoutput.setText("file cant be compiled " +process.getErrorStream());
                        return;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(CodeDoc.class.getName()).log(Level.SEVERE, null, ex);
                }
                 //file is compile and runnable a file is created
                exit=1;
              
        }


    }//GEN-LAST:event_compileAndRunActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    //FONT SETTING
    private void fontSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontSettingActionPerformed
        fontSettings  fS=new fontSettings(CodeDoc.this);
        fS.show();
    }//GEN-LAST:event_fontSettingActionPerformed


    //SAVING FILE
    private void saveDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDocActionPerformed
        
        
        String fileName=JOptionPane.showInputDialog("File name");
        try
        {
                out.println("Save_fileName");
                System.out.println("Sending Data to the server side");
                out.println(fileName);  
                try {
                     String path="D:\\"+fileName; 
                    FileWriter fileWriter=new FileWriter(path);
                    fileWriter.write(compiletextbox.getText());
                    fileWriter.close();
                  
                    
                } catch (Exception ex)
                  {System.out.println("Exception : " + ex);} 
                System.out.println(compiletextbox.getText());
        }
        catch(Exception et)
        {
            System.out.println("exception "+et);
        }
        
        
                        
    }//GEN-LAST:event_saveDocActionPerformed
    
    // OPENING FILE    
    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        
        
        OpenDialogBox  db=new OpenDialogBox(this);
        db.show();
        compiletextbox.setEditable(false);
            
       
    }//GEN-LAST:event_OpenActionPerformed

    private void newDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDocActionPerformed
        compiletextbox.setText("");
    }//GEN-LAST:event_newDocActionPerformed

    private void editDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDocActionPerformed
       compiletextbox.setEditable(true);
    }//GEN-LAST:event_editDocActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       compiletextbox.setText("");
    }//GEN-LAST:event_resetActionPerformed



    private void shareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareButtonActionPerformed
        
    }//GEN-LAST:event_shareButtonActionPerformed

    
    private void compiletextboxCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_compiletextboxCaretUpdate
        // TODO add your handling code here:
        
        if(k == 1 && l== 0 && sender == false){
              codeArea= true;
//            chatArea= false;
            sender= true;
            out.println("Key Pressed");
            String text = compiletextbox.getText();
          
            text = text.replaceAll("\n", "~");
            //System.out.println("Text : "+text);
            out.println(text);
           
        }
        
    }//GEN-LAST:event_compiletextboxCaretUpdate

    
    private void pressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressActionPerformed
        // TODO add your handling code here:
//        codeArea= true;
//        chatArea= false;
        out.println("Share Button Clicked");
        l= 0;
        k = 1;

            Thread th7=new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while(k == 1){
                        String combinedText = in.readLine();
                        System.out.println(combinedText);
                        
                        String text= combinedText.replaceAll("~", "\n");
                        
                        compiletextbox.setText(text);
                        if(sender == true){
                            System.out.println("Mai Senger got true ke andar aaya");
                            int len= compiletextbox.getText().length();
                            System.out.println("Lenght Value : "+len);
                            compiletextbox.setCaretPosition(len);
                            
                            System.out.println("Cursor Position Updated");
                            sender= false;
                        }
                        
                    }
                }
                catch (IOException ex) {
                    System.out.println("Exception thrown : +"+ex);
                }
            }

            });
            th7.start();
        
    }//GEN-LAST:event_pressActionPerformed

    private void releaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releaseActionPerformed
        // TODO add your handling code here:
        //k= 0;
        out.println("Unshare");
    }//GEN-LAST:event_releaseActionPerformed


    private void compiletextboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_compiletextboxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_compiletextboxKeyPressed

    //Send Message
    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
        
        String messg= typeMessg.getText();
        if(messg.equals("")){
            JOptionPane.showMessageDialog(null, "Please Type a Message");
        }
        else{
            codeArea= false;
            chatArea= true;
            messg = messg.replaceAll("\n", "~");
            int length = chatSection.getText().length();
            chatSection.setCaretPosition(length);
            
            out.println("Send Message");
            out.println(messg);
            
            Thread th6=new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while(k == 1 && chatArea){
                        String receivedMssg = in.readLine();
                        System.out.println("In Thread: email: "+LoginWindow.userId+ " and messsage: "+receivedMssg);
                        
                        String text= receivedMssg.replaceAll("~", "\n");
                        
                        chatSection.append(LoginWindow.userId+ " : "+text+"\n"); 
                        typeMessg.setText("");
                    }
                }
                catch (IOException ex) {
                    System.out.println("Exception thrown : +"+ex);
                }
            }

            });
            th6.start();
        }
        
    }//GEN-LAST:event_sendMessageActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeDoc().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Open;
    private javax.swing.JCheckBox autoComplete;
    private javax.swing.JTextArea chatSection;
    private javax.swing.JButton compileAndRun;
    private javax.swing.JTextArea compiletextbox;
    private javax.swing.JButton customInput;
    private javax.swing.JButton editDoc;
    private javax.swing.JButton fontSetting;
    private javax.swing.JTextArea getinput;
    private javax.swing.JTextArea getoutput;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> languageSelector;
    private javax.swing.JButton newDoc;

    private javax.swing.JButton press;
    private javax.swing.JButton release;

    private javax.swing.JButton reset;
    private javax.swing.JButton saveDoc;
    private javax.swing.JButton sendMessage;
    private javax.swing.JButton shareButton;

    private javax.swing.JTextField timer;

    private javax.swing.JTextArea typeMessg;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
